language: node_js
node_js:
  - "8"
  - "9"
cache:
  directories:
    - "node_modules"
addons:
  code_climate:
    repo_token: fed499d92cda5dc352248450b918041edcf13d6db821bb32bd70becf94564576

before_install:
  - npm i -g npm@latest
install:
  - npm install
script:
  - npm test
after_script:
  - npm install -g codeclimate-test-reporter
  - codeclimate-test-reporter < ./coverage/lcov.info