language: node_js
node_js:
  - "8"
  - "9"
cache:
  directories:
    - "node_modules"
addons:
  code_climate:
    repo_token: 1be9acbe2bb25ffd49973460358ee0a93219d8cd747dbe9f4cf6833e30aab096

before_install:
  - npm i -g npm@latest
install:
  - npm install
script:
  - npm test
after_script:
  - npm install -g codeclimate-test-reporter
  - codeclimate-test-reporter < ./coverage/lcov.info