language: node_js
node_js:
  - "12"
  - "13"
cache:
  directories:
    - "node_modules"

env:
  global:
    - CC_TEST_REPORTER_ID=fed499d92cda5dc352248450b918041edcf13d6db821bb32bd70becf94564576
    - EXPRESS_PORT=3000
    - SOCKETIO_PORT=4000

before_install:
  - npm i -g npm@latest
  - curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./cc-test-reporter
  - chmod +x ./cc-test-reporter
  - ./cc-test-reporter before-build
install:
  - npm install

script:
  - npm test
after_script:
  - ./cc-test-reporter after-build --exit-code $TRAVIS_TEST_RESULT