version: '3'

services:
    app:
        build:
            context: ./app
            args:
                node_env: development
        ports:
            - ${EXPRESS_PORT}:3000
            - ${SOCKETIO_PORT}:4000
        volumes:
            - ${APP_PATH}:/var/www/application



